### ISSUE TITLE
image generation

### ISSUE THREAD

**Issue by Mingxiao-Li** [YujieLu10/IACE-NLU#3]
It seems generating images is slow. May I ask how long and how much computation resources did you use to generate images for all dataset ?  Thanks in advanced.

**Comment by YujieLu10** [comment]
It's not fast but should be acceptable by balancing the iteration step and the resolution. If you want a faster generation of high-resolution visual imagination, we suggest you switch to the newly released text-to-image model, e.g., stable-diffusion. Since we're not sure when we have time to support stable-diffusion in our repo, we recommend you try it yourself as well.
